package enum

const (
	BUY = "BUY"
	SELL = "SELL"
	LIMIT = "LIMIT"
	MARKET = "MARKET"
	STOP = "STOP"
	NEW = "NEW"
	PARTIALLY_FILLED = "PARTIALLY_FILLED"
	FILLED = "FILLED"
	CANCELED = "CANCELED"
	PENDING_CANCEL = "PENDING_CANCEL"
	REJECTED = "REJECTED"
	EXPIRED = "EXPIRED"
)
